### ISSUE TITLE
Media path is unreadable

### ISSUE THREAD

**Issue by NataniaBirnbaum** [blackcandy-org/blackcandy#383]
I cannot enter a path in the Library section on the Settings page. I've tried absolute paths from C:/, from the WSL file system, with and without quotation marks. Every path I try to enter makes an error pop up that says that the media path is unreadable. What does that mean? What format should the media path be?

**Comment by aidewoode** [comment]
You should first mount the path that store your music files to the black candy docker container. Then you can use the mounted path as the media path in the setting.  See: https://github.com/blackcandy-org/blackcandy?tab=readme-ov-file#media-files-mounts . I don't know much about WSL, but I think WSL should have a way lets you access files from Windows system to subsystem of Linux.

**Comment by NataniaBirnbaum** [comment]
Thank you, it worked! I saw that part in the readme but I didn't really know what it meant. I have no experience with Docker or servers, so the instructions weren't really intuitive for me.

**Comment by NataniaBirnbaum** [comment]
Thank you, it worked! I saw that part in the readme but I didn't really know what it meant. I have no experience with Docker or servers, so the instructions weren't really intuitive for me.
